---
title: "ProjectWork"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

 **Importing the Data**
 
```{r}
library("readxl")
library(dplyr)
library(tidyverse)
library(ggplot2)
dat <- read_excel("ALL.xlsx")
dat <- select(dat, -Player2, -Player3)
```
Create Variables we need
```{r}
  dat <- mutate(dat, RBIAB = RBI / AB) ##Round these to .000 decimals if possible
  ##Runs batted in per at bat^
  dat <- mutate(dat, HRAB = HR / AB)  ##Round these to .000 decimals if possible
  ##Home Runs per at bat^
  dat <- mutate(dat, BABIP = H - HR / AB - SO - HR + SF) ##Round these to .000 decimals if possible
  ##Batting Average on Balls in Play^
  dat$NP <- as.numeric(dat$NP) ##Cleaning the Data, changing column from character to Number
  dat <- mutate(dat, NPPA = NP / PA)
  ##Number of pitches per plate appearance^
  dat <- mutate(dat, NPAB = NP / AB)
  ##Number of Pitches per At bat per at bat^
```


Visualize the Data
```{r}
ggplot(dat, aes(x = AVG)) + geom_histogram(binwidth = .002,color="Black", fill="light blue") + xlab("Batting Average") + ggtitle("Histogram of Batting Average") + ylab("Count")

ggplot(dat, aes(x = OPS)) + geom_histogram(binwidth = .005,color="Black", fill="light green") + xlab("On-Base + Slugging Percentage") + ggtitle("Histogram of OPS") + ylab("Count")


ggplot(dat, aes(x = RBIAB, y = SLG)) + geom_point(color = 'coral2') + geom_smooth(method='lm',formula=y~x) + xlab("RBI per At bat") + ggtitle("Relationship between Slugging Percentage and RBI's per At Bat") + ylab("Slugging Percentage")## R_SQUARED


ggplot(dat, aes(x = HRAB, y = NPPA)) + geom_point() + geom_smooth(method='lm',formula=y~x) ## R_SQUARED
```
Which position has the best batting average?
```{r}
dat2 <- dat
dat2%>%
  select(Pos, AVG) %>%
  mutate(AVG = ifelse(AVG == -9999, NA, AVG)) %>%
  group_by(Pos) %>%
  mutate(MEANAVG = mean(AVG, na.rm = T)) -> dat2
ggplot(dat2, aes(x = AVG)) + geom_histogram(binwidth = .002,color="Black", fill="goldenrod2") + xlab("Batting Average") + ggtitle("Histogram of Batting Average by Position") + ylab("Count") + facet_wrap(~Pos) + geom_vline(aes(xintercept = MEANAVG))

dat3 <- select(dat2, -AVG)
dat3 <- distinct(dat3)  #ROUND TO 3 digits

head(dat3, 10)
# WOW, This makes no sense, as the lowest batting average on the field is the DH and the Right fielder
```
Following Albert Pujols through his career 
```{r}
Albert <- filter(dat, Player == 'Pujols,A')
```






Does more HRs = less batting AVG?

```{r}

```

Does Avg # of pitches in an at bat correlate with batting Avg? Does it correlate with HRs?

```{r}
ggplot(dat, aes(x = AVG, y = NPAB)) + geom_smooth(method='lm') + geom_point() + xlab("Batting Average") + ggtitle("Relationship Between Average Number of Pitches in an at Bat to Batting Average") + ylab("Average Number of Pitches During an at Bat")## R_SQUARED
```

Who is getting intentionally walked? HR hitters or high avg hitters?

```{r}

```